#! /usr/bin/env php

<?php

use Paracall\Config\TheConfigurator;
use Paracall\Console\Commands\MigrateMakeCommand;
use Paracall\Console\ParacallApp;
use Paracall\Console\Commands\MigrateCommand;
use Paracall\Console\Commands\SayHelloCommand;



require 'vendor/autoload.php';

$app = new ParacallApp('Paracall Igor', '1.0');

$app->setBaseDir(__DIR__);

$app->add(new SayHelloCommand());
$app->add(new MigrateCommand($app->baseDir, $app->getAppNamespace()));
$app->add(new MigrateMakeCommand());
$app->run();